version: '3.8'
services:
  nginx:
    image: ${ECR_REGISTRY}/fib-nginx:${IMAGE_TAG}
    ports:
      - "80:80"
    restart: always
    depends_on: [api, client]

  client:
    image: ${ECR_REGISTRY}/fib-client:${IMAGE_TAG}
    restart: always

  api:
    image: ${ECR_REGISTRY}/fib-api:${IMAGE_TAG}
    restart: always
    environment:
      - REDIS_HOST=${REDIS_HOST}
      - REDIS_PORT=${REDIS_PORT}
      - PGHOST=${PGHOST}
      - PGPORT=${PGPORT}
      - PGUSER=${PGUSER}
      - PGPASSWORD=${PGPASSWORD}
      - PGDATABASE=${PGDATABASE}
      - PORT=8080
      - NODE_ENV=production
  
  worker:
    image: ${ECR_REGISTRY}/fib-worker:${IMAGE_TAG}
    restart: always
    environment:
      - REDIS_HOST=${REDIS_HOST}
      - REDIS_PORT=${REDIS_PORT}
      - NODE_ENV=production