name: Deploy to AWS Elastic Beanstalk
on:
  push:
    branches: [main]

permissions:
  id-token: write
  contents: read

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Configure AWS Credentials via OIDC
        uses: aws-actions/configure-aws-credentials@v2
        with:
          role-to-assume: arn:aws:iam::${{ secrets.AWS_ACCOUNT_ID }}:role/GitHubActionRole-FibCalculator
          aws-region: ${{ secrets.AWS_REGION }}

      - name: Login to Amazon ECR
        id: login-ecr
        uses: aws-actions/amazon-ecr-login@v1

      - name: Build & Push
        env:
          ECR_REGISTRY: ${{ steps.login-ecr.outputs.registry }}
          IMAGE_TAG: ${{ github.sha }}
        run: |
          # Build with the SHA tag
          docker build -t $ECR_REGISTRY/fib-client:$IMAGE_TAG ./client
          docker build -t $ECR_REGISTRY/fib-api:$IMAGE_TAG ./server
          docker build -t $ECR_REGISTRY/fib-worker:$IMAGE_TAG ./worker
          docker build -t $ECR_REGISTRY/fib-nginx:$IMAGE_TAG ./nginx
          
          # Push the SHA tag
          docker push $ECR_REGISTRY/fib-client:$IMAGE_TAG
          docker push $ECR_REGISTRY/fib-api:$IMAGE_TAG
          docker push $ECR_REGISTRY/fib-worker:$IMAGE_TAG
          docker push $ECR_REGISTRY/fib-nginx:$IMAGE_TAG

      - name: Create Deploy Package
        env:
          ECR_REGISTRY: ${{ steps.login-ecr.outputs.registry }}
          IMAGE_TAG: ${{ github.sha }}
        run: |
          envsubst '$ECR_REGISTRY $IMAGE_TAG' < docker-compose.prod.yml > docker-compose.yml
          zip -r deploy.zip docker-compose.yml

      - name: Beanstalk Deploy
        uses: einaregilsson/beanstalk-deploy@v21
        with:
          aws_access_key: ${{ env.AWS_ACCESS_KEY_ID }}
          aws_secret_key: ${{ env.AWS_SECRET_ACCESS_KEY }}
          aws_session_token: ${{ env.AWS_SESSION_TOKEN }}
          application_name: fib-calculator
          environment_name: Fibcalculator-env
          version_label: "v-${{ github.sha }}"
          region: ${{ secrets.AWS_REGION }}
          deployment_package: deploy.zip